### ISSUE TITLE
Distribute "ready-to-use" releases with generated C code

### ISSUE THREAD

**Issue by PiotrSikora** [indutny/llhttp#10]
Even though there is a `make release` target that generates C code and provides `release` directory:
```
$ tree release/
release/
├── common.gypi
├── include
│   └── llhttp.h
├── LICENSE-MIT
├── llhttp.gyp
├── README.md
└── src
    ├── api.c
    ├── http.c
    └── llhttp.c
```
the releases distributed on GitHub are auto-generated from the tags and include only source code.

Would you consider distributing "ready-to-use" releases with generated C code to avoid extra build-time dependencies on consumers of your library? Thanks!

**Comment by indutny** [comment]
Here you go: https://github.com/indutny/llhttp/releases/tag/release%2Fv1.1.0 :wink:

It is automated (in quite awkward way) now.

**Comment by indutny** [comment]
As a matter of fact, all releases will live in `release` branch: https://github.com/indutny/llhttp/tree/release

**Comment by PiotrSikora** [comment]
Thanks!
