### ISSUE TITLE
missing file bin/build.ts ?

### ISSUE THREAD

**Issue by fraxken** [indutny/llhttp#5]
Hi,

The npm command `npm run build` run the following command: `ts-node bin/build.ts`. But the file build.ts doesn't exist. I guess the command is now `ts-node bin/generate.ts` ?

If this is the case, i would be happy to pull-request :) 

Best Regards,
Thomas

**Comment by indutny** [comment]
Should be fixed now. Thank you!

**Comment by indutny** [comment]
Sorry, I went too quick on it and patched it myself. Would love to see your future contributions, nevertheless!
