### ISSUE TITLE
Add function to get HTTP method in string

### ISSUE THREAD

**Issue by tatsuhiro-t** [indutny/llhttp#6]
http-parser has http_method_str which returns HTTP method in string.
It would be nice to add the similar function to llhttp.  I think the following code would work:

```c
const char* llhttp_method_name(llhttp_method_t m) {
#define HTTP_METHOD_GEN(NUM, NAME, STRING) case HTTP_##NAME: return #STRING;
  switch (m) {
    HTTP_METHOD_MAP(HTTP_METHOD_GEN)
    default: abort();
  }
#undef HTTP_METHOD_GEN
}
```

or define string array just like http-parser.

**Comment by indutny** [comment]
That sounds great! Would you mind submitting a PR with this function implementation `api.c` and declaration in `api.h` files? Thanks!

**Comment by tatsuhiro-t** [comment]
I'll submit a PR.  Thank you.
